## Chapter02 - Tokenizing text

In [1]:
# downloading dataset 'the verdict'
import os
import requests

file_path = "the-verdict.txt"
if not os.path.exists(file_path):
    url = ("https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/refs/heads/main/ch02/01_main-chapter-code/the-verdict.txt")

    response = requests.get(url, timeout=30)
    response.raise_for_status()
    # print(response.content)
    with open(file_path, "wb") as f:
        f.write(response.content)

In [2]:
# read the dataset and store it in string
with open(file_path, "r", encoding= "utf-8") as f:
    raw_text = f.read()

print(f"Dataset: \n{raw_text[:1000]}\n")    # first 1000 characters
print(f"Length of the dataset: {len(raw_text)}")

Dataset: 
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)

"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it's going to send the value of my picture 'way up; but I don't think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing's lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn's "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?

Well!--even 

### 2.1 Tokenizing text using regular expression

In [3]:
# Tokenizing using regular expression
import re

input_text = "Hello world, this is a sample text for LLM."

# split the input text based on whitespaces using regular expression (including whitespaces in list)
result = re.split(r'(\s)', input_text)
print(f"Ouput list based on whitespaces(including whitespace): \n{result}\n")

# split the input text based on whitespaces and punctuations 
result = re.split(r'([,.]|\s)', input_text) # split punctuations mentioned as separate tokens
print(f"Ouput list based on whitespaces & punctuations: \n{result}\n")

# strip whitespace from each item and then filter out any empty strings
result = [item for item in result if item.strip()]
print(f"Ouput list based on whitespaces & punctuations(exclusing whitespaces): \n{result}\n")

# handling more complex input text with punctuatuions
complex_text = "Hello, world, Is this a --text?"
result = re.split(r'([,.:;?_!"()\']|--|\s)', complex_text)
result = [item for item in result if item.strip()]
print(f"Ouput list: \n{result}\n")

Ouput list based on whitespaces(including whitespace): 
['Hello', ' ', 'world,', ' ', 'this', ' ', 'is', ' ', 'a', ' ', 'sample', ' ', 'text', ' ', 'for', ' ', 'LLM.']

Ouput list based on whitespaces & punctuations: 
['Hello', ' ', 'world', ',', '', ' ', 'this', ' ', 'is', ' ', 'a', ' ', 'sample', ' ', 'text', ' ', 'for', ' ', 'LLM', '.', '']

Ouput list based on whitespaces & punctuations(exclusing whitespaces): 
['Hello', 'world', ',', 'this', 'is', 'a', 'sample', 'text', 'for', 'LLM', '.']

Ouput list: 
['Hello', ',', 'world', ',', 'Is', 'this', 'a', '--', 'text', '?']



In [4]:
# tokenizing the dataset using regular expression
processed_text = re.split(r'([,."?_!()"\';:]|--|\s)', raw_text)
processed_text = [item for item in processed_text if item.strip()]
print(f"Generated tokens(first 50): {processed_text[:50]}\n")
print(f"Number of tokens generated: {len(processed_text)}")

Generated tokens(first 50): ['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself']

Number of tokens generated: 4690


### 2.2 Generating token IDs using tokenizer

In [5]:
# Tokenizer use a vocabulary which contains a collection of words and their coresponding token ids to generate token ids
# when a new token is given as input, tokenizer finds that token in vocabulary and returns the token id & vice versa

# finding unique tokens from the dataset
unique_tokens = sorted(set(processed_text))
print(f"Unique tokens from dataset: {unique_tokens[:20]}\n")
print(f"Number of the unique tokens present in the dataset: {len(unique_tokens)}\n")

# building a vocabulary which contains <k, v> pairs of str and int
vocabulary = {token:integer for integer, token in enumerate(unique_tokens)}
print(f"Vocabulary generated from dataset: {vocabulary}\n")
print(f"Number of pairs in vocabulary: {len(vocabulary)}\n")

Unique tokens from dataset: ['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be']

Number of the unique tokens present in the dataset: 1130

Vocabulary generated from dataset: {'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte

In [6]:
# Tokenizer which encodes a token (provide token id for given token) & decodes (provides token for given token id) using vocabulary
class SimpleTokenizerV1:
    def __init__(self, vocabulary):
        self.str_to_int = vocabulary        # creating vocabulary for reference for encoding
        self.int_to_str = {integer:token for token, integer in vocabulary.items()}      # creating a inverse vocabulary for decoding
    
    '''
        converts a token into token ids based on the vocabulary
        input: sentence, vocabulary
        ouput: list of token ids for the input sentence
    '''
    def encode(self, input_text):
        # generating tokens from input sentence
        preprocessed = re.split(r'([,."?_!()"\';:]|--|\s)', input_text)
        preprocessed = [item for item in preprocessed if item.strip()]

        # mapping token ids 
        ouput_ids = [self.str_to_int[token] for token in preprocessed]
        return ouput_ids
    
    '''
        converts a token id into token based on inverse vocabulary generated
        input: list of token ids, inverse vocabulary
        output: list of tokens from vocabulary
    '''
    def decode(self, input_ids):
        tokens = " ".join([self.int_to_str[token_id] for token_id in input_ids])
        output_tokens = re.sub(r'\s+([,.?!"()\'])', r'\1', tokens)      # Replace the whitespaces before specified punctuations
        return output_tokens

In [7]:
tokenizer = SimpleTokenizerV1(vocabulary)

sentence = """"It's the last he painted, you know," 
                Mrs. Gisburn said with pardonable pride."""

encoded_text = tokenizer.encode(sentence)
print(f"Token ids generated using tokenizer for \n{sentence}\nis\n{encoded_text}\n")

decoded_text = tokenizer.decode(encoded_text)
print(f"Tokens generated using tokenizer for token list is\n{decoded_text}")

Token ids generated using tokenizer for 
"It's the last he painted, you know," 
                Mrs. Gisburn said with pardonable pride.
is
[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]

Tokens generated using tokenizer for token list is
" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


### 2.3 Adding special context toekns
- The above simple tokenizer fails if the token is not present in the vocabulary 
- To overcome this we can add special context tokens such as `<|unkown|>` for unkown text and `<|endoftext|>` to denote end of text

In [8]:
# failure of toeknizer
error_sentence = "Hello! This sentence fails in tokenizer"
tokenizer.encode(error_sentence)

KeyError: 'Hello'

In [ ]:
# adding special context tokens to the dataset
token_list = sorted(set(processed_text))
token_list.extend(["<|unknown|>", "<|endoftext|>"])

# updated vocabulary
vocabulary_V2 = {token:integer for integer, token in enumerate(token_list)}
print(f"Vocabulary generated from dataset V2: {list(vocabulary_V2.items())[-5:]}\n")
print(f"Number of pairs in vocabulary_V2: {len(vocabulary_V2)}\n")

Vocabulary generated from dataset V2: [('younger', 1127), ('your', 1128), ('yourself', 1129), ('<|unknown|>', 1130), ('<|endoftext|>', 1131)]

Number of pairs in vocabulary_V2: 1132



In [9]:
# Tokenizer which encodes a token (provide token id for given token) & decodes (provides token for given token id) using vocabulary
class SimpleTokenizerV2:
    def __init__(self, vocabulary):
        self.str_to_int = vocabulary        # creating vocabulary for reference for encoding
        self.int_to_str = {integer:token for token, integer in vocabulary.items()}      # creating a inverse vocabulary for decoding
    
    '''
        converts a token into token ids based on the vocabulary
        input: sentence, vocabulary
        ouput: list of token ids for the input sentence
    '''
    def encode(self, input_text):
        # generating tokens from input sentence
        preprocessed = re.split(r'([,."?_!()"\';:]|--|\s)', input_text)
        preprocessed = [item for item in preprocessed if item.strip()]

        # handling unknown tokens
        preprocessed = [
            token if token in self.str_to_int
            else "<|unknown|>"
            for token in preprocessed
        ]

        # mapping token ids 
        ouput_ids = [self.str_to_int[token] for token in preprocessed]
        return ouput_ids
    
    '''
        converts a token id into token based on inverse vocabulary generated
        input: list of token ids, inverse vocabulary
        output: list of tokens from vocabulary
    '''
    def decode(self, input_ids):
        tokens = " ".join([self.int_to_str[token_id] for token_id in input_ids])
        output_tokens = re.sub(r'\s+([,.?!"()\'])', r'\1', tokens)      # Replace the whitespaces before specified punctuations
        return output_tokens

In [10]:
tokenizerV2 = SimpleTokenizerV2(vocabulary_V2)

encoded_text = tokenizerV2.encode(error_sentence)
print(f"Token ids generated using tokenizer v2 for \n{error_sentence}\nis\n{encoded_text}\n")

decoded_text = tokenizerV2.decode(encoded_text)
print(f"Tokens generated using tokenizer v2 for token list is\n{decoded_text}")

NameError: name 'vocabulary_V2' is not defined

### 2.4 Byte pair encoding
- Tiktokenizer library from openAI which uses the byte pair encoding algorithm for tokenizing text is used 
- To learn more about byte pair encoding: [BPE-implementation](https://github.com/rasbt/LLMs-from-scratch/tree/main/ch02/05_bpe-from-scratch)

In [11]:
import tiktoken

tiktoken.__version__

'0.12.0'

In [12]:
gpt2_tokenizer = tiktoken.get_encoding("gpt2")

sentence = "Hello, world!"
encoded_text = gpt2_tokenizer.encode(sentence)
print(f"Token ids generated using tokenizer v2 for \n{sentence}\nis\n{encoded_text}\n")

decoded_text = gpt2_tokenizer.decode(encoded_text)
print(f"Tokens generated using tokenizer v2 for token list is\n{decoded_text}")

Token ids generated using tokenizer v2 for 
Hello, world!
is
[15496, 11, 995, 0]

Tokens generated using tokenizer v2 for token list is
Hello, world!


In [13]:
# The above tokenizer fails for special characters
error_sentence = "Hello, world! <|endoftext|>"

encoded_text = gpt2_tokenizer.encode(error_sentence)
print(f"Token ids generated using tokenizer v2 for \n{error_sentence}\nis\n{encoded_text}\n")

decoded_text = gpt2_tokenizer.decode(encoded_text)
print(f"Tokens generated using tokenizer v2 for token list is\n{decoded_text}")

ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.


In [14]:
# The special characters need to be explicitly allowed in tik token encode function for it to use

encoded_text = gpt2_tokenizer.encode(error_sentence, allowed_special={"<|endoftext|>"})
print(f"Token ids generated using tokenizer v2 for \n{error_sentence}\nis\n{encoded_text}\n")

decoded_text = gpt2_tokenizer.decode(encoded_text)
print(f"Tokens generated using tokenizer v2 for token list is\n{decoded_text}")

Token ids generated using tokenizer v2 for 
Hello, world! <|endoftext|>
is
[15496, 11, 995, 0, 220, 50256]

Tokens generated using tokenizer v2 for token list is
Hello, world! <|endoftext|>


### 2.5 Data sampling with sliding window
- It will be a computing overhead and performance bottleneck for training LLM if we provide all the dataset input tokens at once(which is not possible if the dataset is huge)
- To make training efficient we need to sample data from dataset for training

In [15]:
# tokenize the dataset which is the-verdict.txt file
encoded_text = gpt2_tokenizer.encode(raw_text, allowed_special={'<|endoftext|>'})

print(f"Length of tokens generated from dataset is: {len(encoded_text)}")

Length of tokens generated from dataset is: 5145


In [16]:
# we take a context window of size 'n' and create chunks from dataset token ids into inputs and targets as following example
# LLM predicts one word at a time thus for a given set of input words it predicts the next word(target) 

encoded_sample = encoded_text[:50]      # taking first 50 tokens for illustration
context_window = 4

x = encoded_sample[:context_window]         # sample input chunk
y = encoded_sample[1:context_window+1]      # sample target chunk which contain the next word in the sequence of dataset

print(f"input  x: {x}\n")
print(f"target y:\t{y}")

input  x: [40, 367, 2885, 1464]

target y:	[367, 2885, 1464, 1807]


In [17]:
# One word by another, the prediction would look like as follows:
for i in range(1, context_window+1):
    context = encoded_sample[:i]
    label = encoded_sample[i]

    # token id illustration
    print(f"{context} --------> {label}")
    # word illustration
    print(f"{gpt2_tokenizer.decode(context)} --------> {gpt2_tokenizer.decode([label])}\n")

[40] --------> 367
I -------->  H

[40, 367] --------> 2885
I H --------> AD

[40, 367, 2885] --------> 1464
I HAD -------->  always

[40, 367, 2885, 1464] --------> 1807
I HAD always -------->  thought



- pytorch can be used to implement a simple data loader that iterates over the input dataset and returns the inputs and targets shifted by one

To use GPU, install pytorch compatible with CUDA version present in the system
- use `nvidia-smi` to fins the CUDA version in the system
- use [pytorch website](https://pytorch.org/) to get the pip command
- For CUDA 13.0: `pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130`

In [18]:
import torch
print(f"pyTorch version installed: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

pyTorch version installed: 2.9.1+cu130
CUDA available: True


In [19]:
# Build dataset and dataloader for training the LLM
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
    def __init__(self, input_txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []
        
        # tokenize the input sentence
        token_ids = tokenizer.encode(input_txt, allowed_special={"<|endoftext|>"})

        # use sliding window to create the input and target chunks
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i : i+max_length]
            target_chunk = token_ids[i+1 : i+max_length+1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __getitem__(self, index):
        return self.input_ids[index], self.target_ids[index]
    
    def __len__(self):
        return len(self.input_ids)

In [20]:
def create_dataloader_V1(input_text, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True, num_workers=0):
    # Initialize tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # create dataset
    train_dataset = GPTDatasetV1(input_text, tokenizer, max_length, stride)

    # create dataloader
    dataloader = DataLoader(
        dataset = train_dataset,
        batch_size = batch_size,
        shuffle = shuffle,
        drop_last = drop_last,
        num_workers = num_workers
    )

    return dataloader

In [21]:
# create a dataloader using input dataset "the-verdict.txt"
# dataloader 01 with max_length 4 and stride 1 (i.e) sliding window is moved one token for each input, target pair
train_dataloader = create_dataloader_V1(input_text=raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)

# iterate over dataloader to sample 
train_dataloader_iterator = iter(train_dataloader)
first_bacth = next(train_dataloader_iterator)
print(f"The first batch is:\n{first_bacth}")

second_batch = next(train_dataloader_iterator)
print(f"The second_batch is:\n{second_batch}")

The first batch is:
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]
The second_batch is:
[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [22]:
# the previous example can excessively repeat tokens making the training for LLM inefficient if the stride is less and max_length is high
# dataloader 02 with max_length 4 and stride 4 (i.e) sliding window is moved four token for each input, target pair
train_dataloader_02 = create_dataloader_V1(input_text=raw_text, batch_size=1, max_length=4, stride=4, shuffle=False)

# iterate over dataloader to sample 
train_dataloader_iterator_02 = iter(train_dataloader_02)
first_bacth = next(train_dataloader_iterator_02)
print(f"The first batch is:\n{first_bacth}")

second_batch = next(train_dataloader_iterator_02)
print(f"The second_batch is:\n{second_batch}")

The first batch is:
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]
The second_batch is:
[tensor([[1807, 3619,  402,  271]]), tensor([[ 3619,   402,   271, 10899]])]


#### 2.6 Creating token embeddings
- converting token ids into embeddings of n dimension for efficient floating point arithmetic using embedding layer
- The embedding layer is usually a part of LLM which has weight parameters that are trained in training
- Embedding layer is equivalent to liner layer while the input is given as one-hot encoding for linear layer
- output of embedding layer is equal to one hot encoding with matrix multiplication
- It has a weight matrix of *vocabulary_size x output_dimension* (i.e) one tensor of size *1 x output_dimension* for each token in vocabulary size

In [23]:
# conside an example which has following token ids after tokenization
input_ids = torch.tensor([2,3,5,1])

# consider a small vocabulary size of 6 <word, token> pairs and embedding layer output as 3
vocab_size = 6
output_dim = 3

# embedding layer with the specifications
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

# this results in a weight matrix (vocab_size x output_dim) which are the parameters of embedding layer
print(f"The weight matrix of embedding layer is \n{embedding_layer.weight}\nwith size ({embedding_layer.weight.shape})")

The weight matrix of embedding layer is 
Parameter containing:
tensor([[-0.6833,  0.5341,  0.1683],
        [-0.0099, -1.0738,  0.5830],
        [-0.8333, -1.6990,  0.9470],
        [ 0.5231,  0.5289, -0.1799],
        [-1.4157,  1.0738, -1.7159],
        [-0.3208, -2.1647, -0.2405]], requires_grad=True)
with size (torch.Size([6, 3]))


In [ ]:
# the output embedding for an input token id is given as follows
print(embedding_layer(torch.tensor([3])))       # provides the weight matrix row where index - input id

tensor([[ 0.5231,  0.5289, -0.1799]], grad_fn=<EmbeddingBackward0>)


In [26]:
# output for the input id tensor
print(embedding_layer(input_ids))

tensor([[-0.8333, -1.6990,  0.9470],
        [ 0.5231,  0.5289, -0.1799],
        [-0.3208, -2.1647, -0.2405],
        [-0.0099, -1.0738,  0.5830]], grad_fn=<EmbeddingBackward0>)


In [27]:
# GPT 2 embedding layer 
vocab_size = 50257
output_dim = 256

gpt2_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)


In [29]:
# create a dataloader with batch_size 8 
max_length = 4

gpt2_dataloader = create_dataloader_V1(
    input_text= raw_text,
    batch_size= 8,
    stride= max_length,
    max_length= max_length,
    shuffle= False
)

data_iter = iter(gpt2_dataloader)
inputs, targets = next(data_iter)

In [31]:
print(f"Token IDs: \n{inputs}")
print(f"Shape of input token matrix: {inputs.shape}")

Token IDs: 
tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Shape of input token matrix: torch.Size([8, 4])


In [32]:
gpt2_token_embeddings = gpt2_embedding_layer(inputs)
print(f"The output of embedding layer is \n{gpt2_token_embeddings}\nwith size ({gpt2_token_embeddings.shape})")

The output of embedding layer is 
tensor([[[-3.4108e-01, -3.8784e-01,  9.1211e-01,  ..., -1.9797e-03,
          -2.7667e-01, -5.1067e-01],
         [ 1.8936e+00,  2.4997e-01,  9.1787e-01,  ...,  8.0095e-01,
           5.7264e-01,  1.3926e+00],
         [-9.1654e-01,  5.8086e-01, -1.1929e+00,  ...,  4.8878e-01,
          -1.3636e+00,  1.0079e-01],
         [ 1.2470e+00,  1.5511e+00, -3.6698e-01,  ...,  4.6135e-01,
          -7.7272e-01, -9.2953e-01]],

        [[ 4.7040e-01, -2.4356e+00,  2.6202e-01,  ..., -6.0925e-01,
          -2.4048e-01,  3.1452e-01],
         [ 1.0366e+00, -8.4189e-01, -3.0703e-01,  ..., -5.6300e-02,
          -4.4556e-01,  9.8864e-01],
         [-4.9349e-01,  6.8070e-01,  1.0029e+00,  ...,  8.8406e-01,
          -7.5573e-01, -2.5353e-02],
         [-1.3098e+00, -4.8898e-01,  1.2950e+00,  ...,  1.6271e+00,
           3.9815e-01,  7.3044e-01]],

        [[ 2.3167e+00,  5.9937e-01, -4.5243e-01,  ..., -1.0191e+00,
          -4.0521e-01,  1.5108e+00],
         [ 2.7252

- embedding layer produces identical embeddings for a given token id regardless of their position in the input sentence
- to incorporate positional data into the input, positional embeddings are used 
- positional embeddings is another layer which adds a fixed value taken from weight matrix of that layer to the input id 

In [33]:
# GPT2 uses absolute position embeddings whcih can be implemented by adding another embedding layer
context_length = max_length

positional_embedding_layer = torch.nn.Embedding(context_length, output_dim)
print(f"The weight matrix of positional embedding layer is \n{positional_embedding_layer.weight}\nwith size ({positional_embedding_layer.weight.shape})")

The weight matrix of positional embedding layer is 
Parameter containing:
tensor([[-2.4423,  0.6717, -0.0784,  ..., -2.0067,  0.4322,  0.4043],
        [ 0.7205,  1.3107,  1.0118,  ..., -0.3535,  0.6377, -1.3005],
        [-1.7337,  0.4097, -0.3719,  ..., -1.1086,  1.0429, -0.3293],
        [-0.4874,  0.3231, -0.8114,  ..., -0.5766, -1.5603, -0.1837]],
       requires_grad=True)
with size (torch.Size([4, 256]))


In [36]:
# the context window size of GPT2 is 1024 hence the postional embedding layer will have shape of 1024 x 256 
pos_embeddings = positional_embedding_layer(torch.arange(max_length))
print(f"The output of positional embedding layer is \n{pos_embeddings}\nwith size ({pos_embeddings.shape})")

The output of positional embedding layer is 
tensor([[-2.4423,  0.6717, -0.0784,  ..., -2.0067,  0.4322,  0.4043],
        [ 0.7205,  1.3107,  1.0118,  ..., -0.3535,  0.6377, -1.3005],
        [-1.7337,  0.4097, -0.3719,  ..., -1.1086,  1.0429, -0.3293],
        [-0.4874,  0.3231, -0.8114,  ..., -0.5766, -1.5603, -0.1837]],
       grad_fn=<EmbeddingBackward0>)
with size (torch.Size([4, 256]))


In [37]:
input_embeddings = gpt2_token_embeddings + pos_embeddings
print(f"The output of embedding layers is \n{input_embeddings}\nwith size ({input_embeddings.shape})")

The output of embedding layers is 
tensor([[[-2.7833,  0.2838,  0.8337,  ..., -2.0087,  0.1556, -0.1063],
         [ 2.6142,  1.5607,  1.9296,  ...,  0.4475,  1.2103,  0.0921],
         [-2.6503,  0.9905, -1.5647,  ..., -0.6198, -0.3208, -0.2285],
         [ 0.7596,  1.8741, -1.1784,  ..., -0.1152, -2.3330, -1.1133]],

        [[-1.9719, -1.7640,  0.1836,  ..., -2.6160,  0.1918,  0.7189],
         [ 1.7571,  0.4688,  0.7047,  ..., -0.4098,  0.1921, -0.3119],
         [-2.2272,  1.0904,  0.6310,  ..., -0.2245,  0.2871, -0.3546],
         [-1.7972, -0.1659,  0.4836,  ...,  1.0505, -1.1622,  0.5467]],

        [[-0.1255,  1.2710, -0.5308,  ..., -3.0259,  0.0270,  1.9151],
         [ 0.9931, -0.2166,  0.8736,  ..., -1.1118,  1.1431, -0.8951],
         [-1.5260,  0.6483, -0.6130,  ...,  0.6501, -0.0657, -0.3940],
         [ 0.1954,  0.6259, -3.0030,  ...,  0.7151, -1.2331,  0.3092]],

        ...,

        [[-2.3939,  1.1173,  0.7287,  ...,  0.3680, -1.3094,  1.5634],
         [ 2.1583,  1.